const AnthropicModule = require("@anthropic-ai/sdk");
const { fetchCommits, fetchCommitDetail, parseGitHubRepoUrl } = require("./github");

const Anthropic = AnthropicModule.default || AnthropicModule;

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function buildBand(score) {
  if (score < 0.2) return "Likely Human";
  if (score < 0.5) return "Mixed / Uncertain";
  return "Likely AI-assisted";
}

function textScore(message, additions) {
  const reasons = [];
  let score = 0;
  const text = (message || "").trim();
  const words = text.split(/\s+/).filter(Boolean);
  const lower = text.toLowerCase();

  if (/^(feat|fix|chore|docs|style|refactor|test|build|ci|perf|revert)(\([a-z\-]+\))?!?:\s/i.test(text)) {
    score += 0.25;
    reasons.push("Conventional commit format");
  }

  const templatePhrases = [
    "this commit",
    "this change",
    "the following changes",
    "in order to",
    "as part of this"
  ];

  if (templatePhrases.some((p) => lower.includes(p))) {
    score += 0.3;
    reasons.push("Template-like commit language");
  }

  if (words.length < 3 && additions > 100) {
    score += 0.25;
    reasons.push("Very short message for large code change");
  }

  if (words.length > 40 && additions < 10) {
    score += 0.2;
    reasons.push("Very long message for tiny code change");
  }

  return { score: clamp(score, 0, 1), reasons };
}

function metadataScore(stats, filesCount, elapsedMinutes, sameAuthorBurstCount) {
  const reasons = [];
  let score = 0;

  const additions = stats?.additions || 0;
  const total = stats?.total || 0;

  if (additions > 500) {
    score += 0.25;
    reasons.push("Large burst of additions");
  }

  if (filesCount >= 20 && additions > 300) {
    score += 0.2;
    reasons.push("Large multi-file scaffolding pattern");
  }

  if (elapsedMinutes !== null && elapsedMinutes > 0) {
    const lpm = additions / elapsedMinutes;
    if (lpm > 60) {
      score += 0.35;
      reasons.push(`High velocity (${lpm.toFixed(1)} lines/min)`);
    } else if (lpm > 30) {
      score += 0.2;
      reasons.push(`Elevated velocity (${lpm.toFixed(1)} lines/min)`);
    }
  }

  if (sameAuthorBurstCount >= 3) {
    score += 0.2;
    reasons.push("Rapid same-author commit burst");
  }

  if (total === 0) {
    reasons.push("No diff stats available");
  }

  return { score: clamp(score, 0, 1), reasons };
}

function authorStats(results) {
  const byAuthor = new Map();

  for (const row of results) {
    if (!byAuthor.has(row.author)) {
      byAuthor.set(row.author, { commits: 0, sum: 0, highAi: 0 });
    }
    const entry = byAuthor.get(row.author);
    entry.commits += 1;
    entry.sum += row.score;
    if (row.score >= 0.7) entry.highAi += 1;
  }

  return [...byAuthor.entries()]
    .map(([author, value]) => ({
      author,
      commitsAnalyzed: value.commits,
      avgScore: Number((value.sum / value.commits).toFixed(3)),
      highAiCommits: value.highAi,
      aiDensity: Number(((value.highAi / value.commits) * 100).toFixed(1))
    }))
    .sort((a, b) => b.avgScore - a.avgScore);
}

function bandCounts(results) {
  return results.reduce(
    (acc, row) => {
      acc[row.band] = (acc[row.band] || 0) + 1;
      return acc;
    },
    { "Likely Human": 0, "Mixed / Uncertain": 0, "Likely AI-assisted": 0 }
  );
}

function extractJsonObject(text) {
  const match = String(text || "").match(/\{[\s\S]*\}/);
  if (!match) {
    return null;
  }

  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}

async function llmTieBreak(diff, message, apiKey) {
  if (!apiKey) {
    return { score: -1, reason: "Anthropic API key not provided; LLM tie-breaker skipped." };
  }

  const client = new Anthropic({ apiKey });
  const prompt = [
    "You are an expert AI code detection engine.",
    "Analyze the following Git commit diff and commit message.",
    "Decide whether the code was likely written by a human or generated by an AI coding assistant.",
    "Return only raw JSON with keys score and reason.",
    "score must be a number from 0.0 to 1.0.",
    "reason must be one short sentence.",
    "",
    `Commit Message:\n${message}`,
    "",
    `Diff:\n${diff}`
  ].join("\n");

  try {
    const response = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 200,
      temperature: 0,
      system: "You are a strict code analysis JSON API. Always output raw JSON.",
      messages: [{ role: "user", content: prompt }]
    });

    const rawText = response?.content?.[0]?.text || "";
    const parsed = extractJsonObject(rawText);
    if (!parsed) {
      return { score: -1, reason: "Claude returned invalid JSON for the tie-breaker." };
    }

    const score = Number(parsed.score);
    if (!Number.isFinite(score)) {
      return { score: -1, reason: "Claude response did not include a usable score." };
    }

    return {
      score: clamp(score, 0, 1),
      reason: `${String(parsed.reason || "Claude reviewed the borderline commit.")} [Verified by Claude]`
    };
  } catch (error) {
    return { score: -1, reason: `Claude API call failed: ${error.message || String(error)}` };
  }
}

async function analyzeRepoFromUrl(repoUrl, count, options = {}) {
  const token = options.githubToken;
  const useLlm = Boolean(options.useLlm);
  const apiKey = (options.anthropicApiKey || process.env.ANTHROPIC_API_KEY || "").trim();
  const { owner, repo } = parseGitHubRepoUrl(repoUrl);
  const commits = await fetchCommits(owner, repo, count, token);

  if (!Array.isArray(commits) || commits.length === 0) {
    throw new Error("No commits found for this repository");
  }

  const detailed = await Promise.all(
    commits.map(async (item) => {
      const detail = await fetchCommitDetail(owner, repo, item.sha, token);
      const diffText = Array.isArray(detail.files)
        ? detail.files.map((file) => file.patch || "").filter(Boolean).join("\n\n")
        : "";

      return {
        sha: item.sha,
        shortSha: item.sha.slice(0, 7),
        author: item.commit?.author?.name || "Unknown",
        date: item.commit?.author?.date || null,
        message: item.commit?.message?.split("\n")[0] || "",
        stats: detail.stats || { additions: 0, deletions: 0, total: 0 },
        filesCount: Array.isArray(detail.files) ? detail.files.length : 0,
        diffText
      };
    })
  );

  const byAuthorTimes = new Map();
  for (const c of detailed) {
    if (!byAuthorTimes.has(c.author)) byAuthorTimes.set(c.author, []);
    byAuthorTimes.get(c.author).push(c);
  }

  for (const items of byAuthorTimes.values()) {
    items.sort((a, b) => new Date(a.date) - new Date(b.date));
  }

  const results = [];
  for (let index = 0; index < detailed.length; index += 1) {
    const row = detailed[index];
    const arr = detailed;
    const prev = arr[index + 1] || null;
    const elapsedMinutes = prev && prev.author === row.author && row.date && prev.date
      ? (new Date(row.date) - new Date(prev.date)) / 60000
      : null;

    const authorItems = byAuthorTimes.get(row.author) || [];
    const currentTime = row.date ? new Date(row.date).getTime() : null;
    const sameAuthorBurstCount = currentTime === null
      ? 0
      : authorItems.filter((x) => {
          if (!x.date) return false;
          const deltaMin = Math.abs(currentTime - new Date(x.date).getTime()) / 60000;
          return deltaMin <= 15;
        }).length;

    const t = textScore(row.message, row.stats.additions || 0);
    const m = metadataScore(row.stats, row.filesCount, elapsedMinutes, sameAuthorBurstCount);
    const score = clamp(t.score * 0.45 + m.score * 0.55, 0, 1);
    const reasons = [...t.reasons, ...m.reasons];

    let finalScore = score;
    if (useLlm && score >= 0.35 && score <= 0.5) {
      const llm = await llmTieBreak(row.diffText || row.sha, row.message, apiKey);
      if (llm.score !== -1) {
        finalScore = llm.score;
        reasons.push(llm.reason);
        reasons.push("Local heuristics were borderline, so Claude resolved the commit.");
      }
    }

    const result = {
      hash: row.sha,
      shortHash: row.shortSha,
      author: row.author,
      message: row.message,
      score: Number(finalScore.toFixed(2)),
      band: buildBand(finalScore),
      reasons: reasons.length ? reasons : ["No strong AI signals"]
    };
    results.push(result);
  }

  return {
    repoName: repo,
    owner,
    count: results.length,
    results,
    leaderboard: authorStats(results),
    bands: bandCounts(results),
    mode: useLlm ? "llm" : "offline"
  };
}

module.exports = {
  analyzeRepoFromUrl
};
